# Generated by Django 3.0.5 on 2022-10-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.IntegerField(choices=[('Not Reviewed', 'Not Reviewed'), ('Processing', 'Processing'), ('Done', 'Done'), ('Rejected', 'Rejected')], default=1),
        ),
    ]
