# Generated by Django 3.0.5 on 2022-10-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_auto_20221008_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not Reviewed'), (2, 'Processing'), (3, 'Done'), (4, 'Rejected')], default=1),
        ),
    ]
